name: Android Dev Build

on:
  push:
    branches: [ "dev" ]

jobs:
  android-build:
    name: Android Dev Build
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Show runner info (Windows)
        run: |
          echo %OS%
          node -v
          yarn -v

      - name: Install npm dependencies
        run: yarn install

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Gradle permission
        run: |
          cd android
          chmod +x gradlew

      - name: Build Android JS Bundle
        run: yarn run package-android

      - name: Build Android APK
        run: |
