name: Android Dev Build

on:
  push:

jobs:
  android-build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install npm dependencies
        run: yarn install

      - name: Set Android SDK env
        run: |
          echo ANDROID_HOME=%LOCALAPPDATA%\Android\Sdk >> %GITHUB_ENV%
          echo PATH=%PATH%;%LOCALAPPDATA%\Android\Sdk\platform-tools >> %GITHUB_ENV%

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Grant Gradle permission
        run: |
          cd android
          chmod +x gradlew

      - name: Build Android JS Bundle
        run: yarn run package-android

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug
